name: On-Demand Unit Testing

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: Node.js version to use.
        required: true
        type: choice
        options:
          - '18'
          - '20'
          - '22'
          - '24'
        default: '24'

jobs:
  test:
    name: On-Demand Unit Testing on Node.js v${{ inputs.node-version }}
    uses: WJSoftware/cicd/.github/workflows/npm-test.yml@v0.1.0
    secrets: inherit
    with:
      pwsh: false
      build: false
      node-version: ${{ inputs.node-version }}
