name: Test Pull Request

on:
  pull_request:
    branches:
    - '**'

jobs:
  test:
    name: Unit Testing
    uses: WJSoftware/cicd/.github/workflows/npm-test.yml@v0.1.0
    secrets: inherit
    with:
      pwsh: false
      build: false
