name: Test Pull Request

on:
    pull_request:
        branches:
        - **
    workflow_dispatch:
      inputs:
        node-version:
          description: Node.js version to use.
          required: false
          type: choice
          options:
            - '18'
            - '20'
            - '22'
            - '24'
          default: '24'

jobs:
  test:
    name: Unit Testing
    uses: WJSoftware/cicd/.github/workflows/npm-test.yml@0.1.0
    secrets: inherit
    with:
      pwsh: false
      build: false
      node-version: ${{ inputs.node-version }}
